[package]
name = "deckyfx-dioxus-ipc-bridge-macros"
version = "0.2.0"
edition = "2021"
authors = ["Decky Fx"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/deckyfx/dioxus-ipc-bridge-macros"
description = "Proc macros for deckyfx-dioxus-ipc-bridge"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
