//! Procedural macros for dioxus-ipc-bridge
//!
//! This crate provides the `#[ipc_route]` macro for ergonomic route handler registration.

use proc_macro::TokenStream;
use quote::{quote, format_ident};
use syn::{
    parse_macro_input, ItemFn, Token, Ident, LitStr,
    parse::{Parse, ParseStream},
};

/// Attribute arguments for #[ipc_route]
///
/// Parses: `GET, "/hello/:name"` or `POST, "/submit"`
struct RouteArgs {
    method: Ident,
    _comma: Token![,],
    pattern: LitStr,
}

impl Parse for RouteArgs {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        Ok(RouteArgs {
            method: input.parse()?,
            _comma: input.parse()?,
            pattern: input.parse()?,
        })
    }
}

/// Attribute macro for defining IPC route handlers
///
/// Generates a struct that implements RouteHandler, delegating to your handler function.
///
/// # Syntax
/// ```rust,ignore
/// #[ipc_route(METHOD, "/path/pattern")]
/// fn handler_name(req: &EnrichedRequest) -> Result<IpcResponse, IpcError> {
///     // handler implementation
/// }
/// ```
///
/// # Arguments
/// - `METHOD` - HTTP method identifier (GET, POST, PUT, DELETE, etc.)
/// - `"/path/pattern"` - URL pattern string with optional :params
///
/// # Generated Code
/// This macro generates:
/// 1. A struct named `{FunctionName}Route` (e.g., `HelloHandlerRoute`)
/// 2. RouteHandler trait implementation that calls your function
/// 3. Helper methods for route registration
///
/// # Example
/// ```rust,ignore
/// use dioxus_ipc_bridge_macros::ipc_route;
/// use dioxus_ipc_bridge::prelude::*;
///
/// #[ipc_route(GET, "/hello/:name")]
/// fn hello_handler(req: &EnrichedRequest) -> Result<IpcResponse, IpcError> {
///     let name = req.path_param("name").unwrap();
///     Ok(IpcResponse::ok(serde_json::json!({
///         "message": format!("Hello, {}!", name)
///     })))
/// }
///
/// // Usage:
/// let mut router = IpcRouter::builder().build();
/// router.register("GET", "/hello/:name", Box::new(HelloHandlerRoute));
/// ```
#[proc_macro_attribute]
pub fn ipc_route(attr: TokenStream, item: TokenStream) -> TokenStream {
    // Parse attribute arguments
    let args = parse_macro_input!(attr as RouteArgs);
    let method = args.method;
    let pattern = args.pattern;

    // Parse the function
    let input_fn = parse_macro_input!(item as ItemFn);
    let fn_name = &input_fn.sig.ident;
    let fn_vis = &input_fn.vis;
    let fn_block = &input_fn.block;
    let fn_inputs = &input_fn.sig.inputs;
    let fn_output = &input_fn.sig.output;

    // Generate struct name from function name (e.g., hello_handler -> HelloHandlerRoute)
    let struct_name = format_ident!("{}Route",
        fn_name.to_string()
            .split('_')
            .map(|word| {
                let mut chars = word.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                }
            })
            .collect::<String>()
    );

    // Generate the expanded code
    let expanded = quote! {
        // Keep the original function as a helper
        #fn_vis fn #fn_name(#fn_inputs) #fn_output {
            #fn_block
        }

        // Generate a struct that implements RouteHandler
        #[doc = concat!("Route handler for ", stringify!(#method), " ", #pattern)]
        #[doc = ""]
        #[doc = concat!("Generated by #[ipc_route] macro from function `", stringify!(#fn_name), "`")]
        #fn_vis struct #struct_name;

        impl dioxus_ipc_bridge::router::RouteHandler for #struct_name {
            fn handle(&self, req: &dioxus_ipc_bridge::request::EnrichedRequest)
                -> Result<dioxus_ipc_bridge::response::IpcResponse, dioxus_ipc_bridge::response::IpcError>
            {
                #fn_name(req)
            }
        }

        impl #struct_name {
            /// Get the HTTP method for this route
            #[allow(dead_code)]
            pub const fn method() -> &'static str {
                stringify!(#method)
            }

            /// Get the URL pattern for this route
            #[allow(dead_code)]
            pub const fn pattern() -> &'static str {
                #pattern
            }

            /// Register this route with a router
            #[allow(dead_code)]
            pub fn register(router: &mut dioxus_ipc_bridge::router::IpcRouter) {
                router.route(Self::method(), Self::pattern(), Box::new(Self));
            }
        }
    };

    TokenStream::from(expanded)
}
